# This is a basic workflow to help you get started with Actions

name: Mac Code Sign

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Download Axon Ivy Designer
        uses: ethanjli/cached-download-action@v0.1.3
        with:
           url: https://developer.axonivy.com/permalink/nightly-13.2/axonivy-designer-linux.zip
           destination: /tmp/downloads-cache/axonivy-designer-linux-nightly.zip

      - name: Unzip
        run: |
          mkdir -p dist
          unzip /tmp/downloads-cache/axonivy-designer-linux-nightly.zip -d dist

      - name: Sign Axon Ivy Designer
        uses: indygreg/apple-code-sign-action@v1
        with:
          input_path: AxonIvyDesigner.app
          output_path: dist/AxonIvyDesigner.app
     
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
